- name: variables
  hosts: web
  vars:
    course: "Devops with AWS"
    duration: 120hrs
    trainer: sivakumar
  tasks:
  - name: print the variable
    ansible.builtin.debug:
       msg: "Course is duration is and trainer is"