- name: variables
  hosts: local
  connection: local
  vars:
    course: "Devops with AWS"
    duration: 120hrs
    trainer: sivakumar
  tasks:
  - name: print the variable
    ansible.builtin.debug:
       msg: "Course is {{ course }} duration is {{ 120hrs }} and trainer is {{sivakumar}}"